//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

@class NSString, Protocol;

@protocol NSObject
- (id)autorelease;
- (Class)class;
- (_Bool)conformsToProtocol:(Protocol *)arg1;
@property(nonatomic, readonly) NSString *description;
@property(nonatomic, readonly) long long hash;
- (_Bool)isEqual:(id)arg1;
- (_Bool)isKindOfClass:(Class)arg1;
- (_Bool)isMemberOfClass:(Class)arg1;
- (_Bool)isProxy;
- (id *)performSelector:(SEL)arg1;
- (id *)performSelector:(SEL)arg1 withObject:(id)arg2;
- (id *)performSelector:(SEL)arg1 withObject:(id)arg2 withObject:(id)arg3;
- (void)release;
- (_Bool)respondsToSelector:(SEL)arg1;
- (id)retain;
- (long long)retainCount;
- (id)self;
@property(nonatomic, readonly) Class superclass;
- (void *)zone;

@optional
@property(nonatomic, readonly) NSString *debugDescription;
@end

